[versions]
caffeine = "3.2.3"
checkstyle = "12.1.2"
commons-beanutils = "1.11.0"
commons-compress = "1.28.0"
commons-io = "2.20.0"
google-java-format = "1.28.0"
guava = "33.5.0-jre"
jackson-datatype-jsr310 = "2.19.2"
jedis = "7.0.0"
jedis-mock = "1.1.12"
jgit = "7.4.0.202509020913-r"
junit = "6.0.1"
kotlin = "2.2.21"
kotlin-logging = "7.0.13"
ktfmt = "0.59"
ktlint = "1.8.0"
micrometer-registry-new-relic = "0.10.0"
mockk = "1.14.6"
newrelic = "8.25.0"
node = "24.6.0"
okhttp3 = "5.3.2"
scribejava-core = "8.3.3"
snakeyaml = "2.5"
spotbugs = "4.8.6"
spring-cloud-starter-contract-stub-runner = "4.3.0"
spring-data-redis = "4.0.0"
spring-security-test = "7.0.0"
twitter-api-java-sdk = "2.0.3"

[libraries]
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
commons-beanutils = { module = "commons-beanutils:commons-beanutils", version.ref = "commons-beanutils" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
google-java-format = { module = "com.google.googlejavaformat:google-java-format", version.ref = "google-java-format"}
guava = { module = "com.google.guava:guava", version.ref = "guava"}
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson-datatype-jsr310" }
java-faker = { module = "com.github.javafaker:javafaker", version = "1.0.2" }
jedis = { module = "redis.clients:jedis", version.ref = "jedis" }
jedis-mock = { module = "com.github.fppt:jedis-mock", version.ref = "jedis-mock" }
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
micrometer-registry-new-relic = { module = "com.newrelic.telemetry:micrometer-registry-new-relic", version.ref = "micrometer-registry-new-relic" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
newrelic-api = { module = "com.newrelic.agent.java:newrelic-api", version.ref = "newrelic" }
newrelic-agent = { module = "com.newrelic.agent.java:newrelic-agent", version.ref = "newrelic" }
okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
scribe-java = { module = "com.github.scribejava:scribejava-core", version.ref = "scribejava-core" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
spotbugs = { module =  "com.github.spotbugs:spotbugs", version.ref = "spotbugs" }
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs" }
spring-cloud-starter-contract-stub-runner = { module = "org.springframework.cloud:spring-cloud-starter-contract-stub-runner", version.ref = "spring-cloud-starter-contract-stub-runner" }
spring-data-redis = { module = "org.springframework.data:spring-data-redis", version.ref = "spring-data-redis" }
spring-security-test = { module = "org.springframework.security:spring-security-test", version.ref = "spring-security-test" }
twitter-api-java-sdk = { module = "com.twitter:twitter-api-java-sdk", version.ref = "twitter-api-java-sdk" }

[bundles]
redis = [ "jedis", "spring-data-redis" ]

[plugins]
ca-cutterslade-analyze = { id = "ca.cutterslade.analyze", version = "2.0.0" }
docker-gradle = { id = "com.bmuschko.docker-remote-api", version = "9.4.0" }
git-publish = { id = "org.ajoberstar.git-publish", version = "5.1.2" }
gradle-git-properties = { id = "com.gorylenko.gradle-git-properties", version = "2.5.2" }
heroku-gradle = { id = "com.heroku.sdk.heroku-gradle", version = "3.0.0" }
kover = { id = "org.jetbrains.kotlinx.kover", version = "0.9.3" }
kotlin-gradle = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
node-gradle = { id = "com.github.node-gradle.node", version = "7.1.0" }
spotbugs-gradle = { id = "com.github.spotbugs", version = "6.2.5" }
spotless = { id = "com.diffplug.spotless", version = "7.2.1" }
spring-boot = { id = "org.springframework.boot", version = "4.0.0" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }
versions-gradle = { id = "com.github.ben-manes.versions", version = "0.51.0" }
